
"use client";

import { useState, useEffect } from "react";
import { generateAiExplanation } from "@/ai/flows/ai-generated-explanation";
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, Loader2, Quote } from "lucide-react";
import { CityRiskData } from "@/data/mock-data";

interface AIExplanationPanelProps {
  cityData: CityRiskData;
}

export function AIExplanationPanel({ cityData }: AIExplanationPanelProps) {
  const [explanation, setExplanation] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    async function getExplanation() {
      setLoading(true);
      try {
        const result = await generateAiExplanation({
          city: cityData.city,
          ehri: cityData.ehri,
          pollutionStress: cityData.pollutionStress,
          heatStress: cityData.heatStress,
          humidityStress: cityData.humidityStress,
          topFactors: cityData.topFactors,
        });
        setExplanation(result);
      } catch (error) {
        setExplanation(cityData.explanation);
      } finally {
        setLoading(false);
      }
    }
    getExplanation();
  }, [cityData]);

  return (
    <div className="relative group">
      <div className="absolute -inset-1 bg-gradient-to-r from-primary/5 via-foreground/5 to-primary/5 rounded-[2.5rem] blur-xl opacity-25 group-hover:opacity-40 transition duration-1000" />
      <Card className="border-none shadow-[0_8px_30px_rgb(0,0,0,0.02)] rounded-[2rem] bg-card/80 backdrop-blur-md relative overflow-hidden">
        <CardContent className="p-10 md:p-14">
          <div className="flex items-center gap-3 mb-8">
            <div className="p-2.5 bg-foreground/5 rounded-2xl">
              <Sparkles className="w-5 h-5 text-foreground/70" />
            </div>
            <span className="text-[11px] font-bold uppercase tracking-[0.2em] text-muted-foreground">
              Cognitive Synthesis Analysis
            </span>
          </div>

          {loading ? (
            <div className="flex flex-col items-center justify-center py-12 gap-6">
              <Loader2 className="w-8 h-8 animate-spin text-primary/20" />
              <span className="text-[10px] font-bold text-muted-foreground animate-pulse tracking-[0.3em] uppercase">
                Aggregating Global Environmental Intelligence...
              </span>
            </div>
          ) : (
            <div className="relative space-y-8">
              <Quote className="absolute -top-6 -left-8 w-16 h-16 text-foreground/5" />
              <p className="text-xl md:text-2xl leading-relaxed text-foreground font-headline font-medium tracking-tight pr-6">
                {explanation}
              </p>
              <div className="flex items-center gap-4 pt-4">
                 <div className="h-px w-12 bg-border" />
                 <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Generated by EHRI-Agent L-720</span>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
