
"use client";

import { useState, useEffect } from "react";
import { generateAiExplanation } from "@/ai/flows/ai-generated-explanation";
import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, Loader2, Quote } from "lucide-react";
import { CityRiskData } from "@/data/mock-data";

interface AIExplanationPanelProps {
  cityData: CityRiskData;
}

export function AIExplanationPanel({ cityData }: AIExplanationPanelProps) {
  const [explanation, setExplanation] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    async function getExplanation() {
      setLoading(true);
      try {
        const result = await generateAiExplanation({
          city: cityData.city,
          ehri: cityData.ehri,
          pollutionStress: cityData.pollutionStress,
          heatStress: cityData.heatStress,
          humidityStress: cityData.humidityStress,
          topFactors: cityData.topFactors,
        });
        setExplanation(result);
      } catch (error) {
        setExplanation(cityData.explanation);
      } finally {
        setLoading(false);
      }
    }
    getExplanation();
  }, [cityData]);

  return (
    <Card className="border-none shadow-[0_4px_20px_rgba(0,0,0,0.03)] rounded-2xl bg-card h-full relative overflow-hidden">
      <div className="absolute top-0 left-0 w-1 h-full bg-foreground/10" />
      <CardContent className="p-8 flex flex-col h-full">
        <div className="flex items-center gap-2 mb-6">
          <div className="p-2 bg-muted rounded-xl">
            <Sparkles className="w-4 h-4 text-foreground/70" />
          </div>
          <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
            Scientific Synthesis
          </span>
        </div>

        {loading ? (
          <div className="flex flex-col items-center justify-center flex-1 gap-4 py-8">
            <Loader2 className="w-6 h-6 animate-spin text-muted-foreground/30" />
            <span className="text-xs font-semibold text-muted-foreground animate-pulse tracking-wide uppercase">
              Analyzing Environmental Corpus...
            </span>
          </div>
        ) : (
          <div className="relative">
            <Quote className="absolute -top-4 -left-4 w-8 h-8 text-foreground/5" />
            <p className="text-[15px] leading-relaxed text-foreground font-medium italic pr-4">
              {explanation}
            </p>
            <div className="mt-8 flex items-center gap-2">
               <span className="w-6 h-[1px] bg-border" />
               <span className="text-[9px] font-bold uppercase tracking-widest text-muted-foreground">Generated by EHRI-Agent v2.4</span>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
